-- Seed sample therapist data
INSERT INTO public.therapists (
  full_name,
  credentials,
  specializations,
  bio,
  years_experience,
  gender,
  languages,
  therapy_approaches,
  session_rate_min,
  session_rate_max,
  accepts_insurance,
  insurance_providers,
  timezone,
  email,
  is_accepting_clients,
  verified,
  city,
  state,
  latitude,
  longitude
) VALUES
(
  'Dr. Sarah Mitchell',
  'PhD, Licensed Clinical Psychologist',
  ARRAY['Anxiety', 'Depression', 'Trauma/PTSD'],
  'I specialize in evidence-based treatments for anxiety and trauma. My approach is warm, collaborative, and focused on helping you develop practical coping skills while processing difficult experiences.',
  12,
  'Female',
  ARRAY['English', 'Spanish'],
  ARRAY['Cognitive Behavioral Therapy (CBT)', 'EMDR', 'Mindfulness-Based Therapy'],
  150,
  200,
  true,
  ARRAY['Blue Cross', 'Aetna', 'United Healthcare'],
  'America/New_York',
  'sarah.mitchell@example.com',
  true,
  true,
  'New York',
  'NY',
  40.7128,
  -74.006
),
(
  'Dr. James Chen',
  'PsyD, Licensed Psychologist',
  ARRAY['Depression', 'Relationship Issues', 'Work/Career Stress'],
  'I work with individuals and couples to navigate life transitions, improve relationships, and manage stress. My style is direct yet compassionate, helping you gain insight and make meaningful changes.',
  8,
  'Male',
  ARRAY['English', 'Mandarin'],
  ARRAY['Psychodynamic Therapy', 'Solution-Focused Therapy', 'Cognitive Behavioral Therapy (CBT)'],
  120,
  180,
  true,
  ARRAY['Cigna', 'Blue Cross'],
  'America/Los_Angeles',
  'james.chen@example.com',
  true,
  true,
  'Los Angeles',
  'CA',
  34.0522,
  -118.2437
),
(
  'Maria Rodriguez',
  'LCSW, Licensed Clinical Social Worker',
  ARRAY['Anxiety', 'Self-Esteem', 'Life Transitions'],
  'I believe in the power of a strong therapeutic relationship. Together, we will explore your strengths and work towards your goals in a safe, non-judgmental space.',
  6,
  'Female',
  ARRAY['English', 'Spanish'],
  ARRAY['Cognitive Behavioral Therapy (CBT)', 'Dialectical Behavior Therapy (DBT)', 'Mindfulness-Based Therapy'],
  100,
  150,
  true,
  ARRAY['Aetna', 'United Healthcare'],
  'America/Chicago',
  'maria.rodriguez@example.com',
  true,
  true,
  'Chicago',
  'IL',
  41.8781,
  -87.6298
),
(
  'Dr. Michael Thompson',
  'MD, Psychiatrist',
  ARRAY['Depression', 'Anxiety', 'Addiction'],
  'As a psychiatrist, I provide both medication management and therapy. I take a holistic approach, considering biological, psychological, and social factors in treatment.',
  15,
  'Male',
  ARRAY['English'],
  ARRAY['Cognitive Behavioral Therapy (CBT)', 'Psychodynamic Therapy'],
  200,
  250,
  true,
  ARRAY['Blue Cross', 'Aetna', 'Cigna', 'United Healthcare'],
  'America/New_York',
  'michael.thompson@example.com',
  true,
  true,
  'New York',
  'NY',
  40.7128,
  -74.0059
),
(
  'Dr. Emily Park',
  'PhD, Licensed Psychologist',
  ARRAY['Trauma/PTSD', 'Grief/Loss', 'Anxiety'],
  'I specialize in trauma-focused therapy using EMDR and other evidence-based approaches. My goal is to help you heal from past experiences and build resilience for the future.',
  10,
  'Female',
  ARRAY['English', 'Korean'],
  ARRAY['EMDR', 'Cognitive Behavioral Therapy (CBT)', 'Mindfulness-Based Therapy'],
  140,
  190,
  false,
  ARRAY[]::text[],
  'America/Los_Angeles',
  'emily.park@example.com',
  true,
  true,
  'Los Angeles',
  'CA',
  34.0522,
  -118.244
),
(
  'Alex Johnson',
  'LMFT, Licensed Marriage and Family Therapist',
  ARRAY['Relationship Issues', 'Family/Couples Therapy', 'Life Transitions'],
  'I work with individuals, couples, and families to improve communication, resolve conflicts, and strengthen relationships. My approach is systemic and solution-focused.',
  7,
  'Non-binary',
  ARRAY['English'],
  ARRAY['Family/Couples Therapy', 'Solution-Focused Therapy', 'Cognitive Behavioral Therapy (CBT)'],
  110,
  160,
  true,
  ARRAY['Aetna', 'Blue Cross'],
  'America/Denver',
  'alex.johnson@example.com',
  true,
  true,
  'Denver',
  'CO',
  39.7392,
  -104.9903
);
